apiVersion: apps/v1
kind: Deployment
metadata:
  name: feria-app
  namespace: feria
  labels:
    app.kubernetes.io/name: feria-app
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: klaforge

spec:
  replicas: 1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app.kubernetes.io/name: feria-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: feria-app
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: klaforge

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: feria-app
          image: ghcr.io/klaforge/feria-app:sha-e033c3d
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          env:
            - name: NODE_ENV
              value: production

            - name: PORT
              value: "3000"

            - name: HOSTNAME
              value: "0.0.0.0"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: feria-postgres
                  key: DATABASE_URL

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}