apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: klaforge-feria
  namespace: argocd
  labels:
    app.kubernetes.io/name: feria-app
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: klaforge
spec:
  project: default

  source:
    repoURL: https://github.com/KLAForge/klaforge-gitops.git
    targetRevision: main
    path: applications/feria

  destination:
    server: https://kubernetes.default.svc
    namespace: feria

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true