apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: klaforge-test-web
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KLAForge/klaforge-gitops.git
    targetRevision: main
    path: applications/test-web

  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false
